config_global_categories = [
    'config system global',
    'config system accprofile',
    'config system np6xlite',
    'config system interface',
    'config system physical-switch',
    'config system custom-language',
    'config system admin',
    'config system sso-admin',
    'config system ha',
    'config system dns',
    'config system replacemsg-image',
    'config system replacemsg mail "partial"',
    'config system replacemsg http "url-block"',
    'config system replacemsg http "urlfilter-err"',
    'config system replacemsg http "infcache-block"',
    'config system replacemsg http "http-contenttypeblock"',
    'config system replacemsg http "https-invalid-cert-block"',
    'config system replacemsg http "https-untrusted-cert-block"',
    'config system replacemsg http "https-blocklisted-cert-block"',
    'config system replacemsg http "switching-protocols-block"',
    'config system replacemsg http "http-antiphish-block"',
    'config system replacemsg http "videofilter-block"',
    'config system replacemsg webproxy "deny"',
    'config system replacemsg webproxy "user-limit"',
    'config system replacemsg webproxy "auth-challenge"',
    'config system replacemsg webproxy "auth-login-fail"',
    'config system replacemsg webproxy "auth-group-info-fail"',
    'config system replacemsg webproxy "http-err"',
    'config system replacemsg webproxy "auth-ip-blackout"',
    'config system replacemsg webproxy "ztna-block"',
    'config system replacemsg ftp "ftp-explicit-banner"',
    'config system replacemsg fortiguard-wf "ftgd-block"',
    'config system replacemsg fortiguard-wf "ftgd-ovrd"',
    'config system replacemsg fortiguard-wf "ftgd-quota"',
    'config system replacemsg fortiguard-wf "ftgd-warning"',
    'config system replacemsg spam "ipblocklist"',
    'config system replacemsg spam "smtp-spam-dnsbl"',
    'config system replacemsg spam "smtp-spam-feip"',
    'config system replacemsg spam "smtp-spam-helo"',
    'config system replacemsg spam "smtp-spam-emailblock"',
    'config system replacemsg spam "smtp-spam-mimeheader"',
    'config system replacemsg spam "reversedns"',
    'config system replacemsg spam "smtp-spam-ase"',
    'config system replacemsg spam "submit"',
    'config system replacemsg alertmail "alertmail-virus"',
    'config system replacemsg alertmail "alertmail-block"',
    'config system replacemsg alertmail "alertmail-nids-event"',
    'config system replacemsg alertmail "alertmail-crit-event"',
    'config system replacemsg alertmail "alertmail-disk-full"',
    'config system replacemsg admin "pre_admin-disclaimer-text"',
    'config system replacemsg admin "post_admin-disclaimer-text"',
    'config system replacemsg auth "auth-disclaimer-page-1"',
    'config system replacemsg auth "auth-disclaimer-page-2"',
    'config system replacemsg auth "auth-disclaimer-page-3"',
    'config system replacemsg auth "auth-proxy-reject-page"',
    'config system replacemsg auth "auth-reject-page"',
    'config system replacemsg auth "auth-login-page"',
    'config system replacemsg auth "auth-login-failed-page"',
    'config system replacemsg auth "auth-token-login-page"',
    'config system replacemsg auth "auth-token-login-failed-page"',
    'config system replacemsg auth "auth-success-msg"',
    'config system replacemsg auth "auth-challenge-page"',
    'config system replacemsg auth "auth-keepalive-page"',
    'config system replacemsg auth "auth-portal-page"',
    'config system replacemsg auth "auth-password-page"',
    'config system replacemsg auth "auth-fortitoken-page"',
    'config system replacemsg auth "auth-next-fortitoken-page"',
    'config system replacemsg auth "auth-email-token-page"',
    'config system replacemsg auth "auth-sms-token-page"',
    'config system replacemsg auth "auth-email-harvesting-page"',
    'config system replacemsg auth "auth-email-failed-page"',
    'config system replacemsg auth "auth-cert-passwd-page"',
    'config system replacemsg auth "auth-guest-print-page"',
    'config system replacemsg auth "auth-guest-email-page"',
    'config system replacemsg auth "auth-success-page"',
    'config system replacemsg auth "auth-block-notification-page"',
    'config system replacemsg auth "auth-quarantine-page"',
    'config system replacemsg auth "auth-qtn-reject-page"',
    'config system replacemsg auth "auth-saml-page"',
    'config system replacemsg sslvpn "sslvpn-login"',
    'config system replacemsg sslvpn "sslvpn-header"',
    'config system replacemsg sslvpn "sslvpn-limit"',
    'config system replacemsg sslvpn "hostcheck-error"',
    'config system replacemsg sslvpn "sslvpn-provision-user"',
    'config system replacemsg sslvpn "sslvpn-provision-user-sms"',
    'config system replacemsg nac-quar "nac-quar-virus"',
    'config system replacemsg nac-quar "nac-quar-dos"',
    'config system replacemsg nac-quar "nac-quar-ips"',
    'config system replacemsg nac-quar "nac-quar-dlp"',
    'config system replacemsg nac-quar "nac-quar-admin"',
    'config system replacemsg nac-quar "nac-quar-app"',
    'config system replacemsg traffic-quota "per-ip-shaper-block"',
    'config system replacemsg utm "virus-html"',
    'config system replacemsg utm "client-virus-html"',
    'config system replacemsg utm "virus-text"',
    'config system replacemsg utm "dlp-html"',
    'config system replacemsg utm "dlp-text"',
    'config system replacemsg utm "appblk-html"',
    'config system replacemsg utm "ipsblk-html"',
    'config system replacemsg utm "ipsfail-html"',
    'config system replacemsg utm "exe-text"',
    'config system replacemsg utm "waf-html"',
    'config system replacemsg utm "outbreak-prevention-html"',
    'config system replacemsg utm "outbreak-prevention-text"',
    'config system replacemsg utm "external-blocklist-html"',
    'config system replacemsg utm "external-blocklist-text"',
    'config system replacemsg utm "ems-threat-feed-html"',
    'config system replacemsg utm "ems-threat-feed-text"',
    'config system replacemsg utm "file-filter-html"',
    'config system replacemsg utm "file-filter-text"',
    'config system replacemsg utm "file-size-text"',
    'config system replacemsg utm "transfer-size-text"',
    'config system replacemsg utm "internal-error-text"',
    'config system replacemsg utm "archive-block-html"',
    'config system replacemsg utm "archive-block-text"',
    'config system replacemsg utm "file-av-fail-text"',
    'config system replacemsg utm "transfer-av-fail-text"',
    'config system replacemsg utm "banned-word-html"',
    'config system replacemsg utm "banned-word-text"',
    'config system replacemsg utm "block-html"',
    'config system replacemsg utm "block-text"',
    'config system replacemsg utm "decompress-limit-text"',
    'config system replacemsg utm "dlp-subject-text"',
    'config system replacemsg utm "file-size-html"',
    'config system replacemsg utm "client-file-size-html"',
    'config system replacemsg icap "icap-req-resp"',
    'config system replacemsg automation "automation-email"',
    'config system snmp sysinfo',
    'config system central-management',
    'config firewall wildcard-fqdn custom',
    'config firewall internet-service-name',
    'config firewall internet-service-definition',
    'config certificate ca',
    'config certificate local',
    'config ips sensor',
    'config application list',
    'config dlp sensor',
    'config antivirus profile',
    'config file-filter profile',
    'config webfilter profile',
    'config webfilter search-engine',
    'config system resource-limits',
    'config system vdom-property',
    'config log tap-device',
    'config firewall ssh local-key',
    'config firewall ssh local-ca',
    'config system cluster-sync',
    'config system fortiguard',
    'config endpoint-control fctems',
    'config system email-server',
    'config system session-helper',
    'config system auto-install',
    'config system console',
    'config system ntp',
    'config system ftm-push',
    'config system automation-trigger',
    'config system automation-action',
    'config system automation-stitch',
    'config system federated-upgrade',
    'config system ike',
]