from urllib.parse import urljoin

class WebUiState:
    def __init__(self, api):
        self.api = api

    def get(self):
        path = 'monitor/web-ui/state'
        url = urljoin(self.api.base_url, path)
        let = self.api.req(url, method='get')

        if let['code'] == 0:
            let['msg'] = f'{path} {self.api.fg_addr}'
        else:
            let['msg'] = f'[Error] Fail {path} {self.api.fg_addr}'

        return let

    def __sample(self):
        sample_response = """
{
  "http_method":"GET",
  "results":{
    "model_name":"FortiGate",
    "model_number":"60F",
    "hostname":"FG60F-Primary",
    "model":"FGT60F",
    "model_subtype":"",
    "model_level":"low",
    "admin_using_default_password":False,
    "admin":{
      "name":"admin",
      "login_name":"admin",
      "profile":{
        "name":"super_admin",
        "q_origin_key":"super_admin",
        "scope":"global",
        "comments":"",
        "secfabgrp":"read-write",
        "ftviewgrp":"read-write",
        "authgrp":"read-write",
        "sysgrp":"read-write",
        "netgrp":"read-write",
        "loggrp":"read-write",
        "fwgrp":"read-write",
        "vpngrp":"read-write",
        "utmgrp":"read-write",
        "wifi":"read-write",
        "netgrp-permission":{
          "cfg":"none",
          "packet-capture":"none",
          "route-cfg":"none"
        },
        "sysgrp-permission":{
          "admin":"none",
          "upd":"none",
          "cfg":"none",
          "mnt":"none"
        },
        "fwgrp-permission":{
          "policy":"none",
          "address":"none",
          "service":"none",
          "schedule":"none",
          "others":"none"
        },
        "loggrp-permission":{
          "config":"none",
          "data-access":"none",
          "report-access":"none",
          "threat-weight":"none"
        },
        "utmgrp-permission":{
          "antivirus":"none",
          "ips":"none",
          "webfilter":"none",
          "emailfilter":"none",
          "data-loss-prevention":"none",
          "file-filter":"none",
          "application-control":"none",
          "icap":"none",
          "voip":"none",
          "waf":"none",
          "dnsfilter":"none",
          "endpoint-control":"none"
        },
        "admintimeout-override":"disable",
        "admintimeout":0,
        "system-diagnostics":"enable"
      },
      "global_admin":True,
      "super_admin":True,
      "ignore_release_overview":"7.0.0",
      "ignore_invalid_signature_version":"",
      "dashboard_template":"minimal",
      "guest_admin":False,
      "fmg_admin":False,
      "sso_login_type":"none",
      "remote_admin":False,
      "pki_admin":False,
      "vdoms":[
        "root"
      ],
      "vdom_info":{
        "root":{
          "central_nat_enabled":False,
          "transparent_mode":False,
          "ngfw_mode":"profile-based",
          "features":{
            "gui-icap":False,
            "gui-implicit-policy":True,
            "gui-dns-database":False,
            "gui-load-balance":False,
            "gui-multicast-policy":False,
            "gui-dos-policy":False,
            "gui-object-colors":True,
            "gui-voip-profile":False,
            "gui-ap-profile":True,
            "gui-security-profile-group":False,
            "gui-local-in-policy":False,
            "gui-explicit-proxy":False,
            "gui-dynamic-routing":False,
            "gui-sslvpn-personal-bookmarks":False,
            "gui-sslvpn-realms":False,
            "gui-policy-based-ipsec":False,
            "gui-threat-weight":True,
            "gui-spamfilter":False,
            "gui-file-filter":True,
            "gui-application-control":True,
            "gui-ips":True,
            "gui-endpoint-control":True,
            "gui-endpoint-control-advanced":False,
            "gui-dhcp-advanced":True,
            "gui-vpn":True,
            "gui-wireless-controller":True,
            "gui-switch-controller":True,
            "gui-fortiap-split-tunneling":False,
            "gui-webfilter-advanced":False,
            "gui-traffic-shaping":True,
            "gui-wan-load-balancing":True,
            "gui-antivirus":True,
            "gui-webfilter":True,
            "gui-videofilter":True,
            "gui-dnsfilter":True,
            "gui-waf-profile":False,
            "gui-fortiextender-controller":True,
            "gui-advanced-policy":False,
            "gui-allow-unnamed-policy":False,
            "gui-email-collection":False,
            "gui-multiple-interface-policy":False,
            "gui-policy-disclaimer":False,
            "gui-ztna":False
          },
          "virtual_wire_pair_count":0,
          "is_management_vdom":True,
          "log_device_state":{
            "memory":{
              "is_available":True,
              "is_enabled":True,
              "is_default":True,
              "is_ha_supported":True
            },
            "disk":{
              "is_available":False,
              "is_enabled":False,
              "is_loggable":False,
              "num_ssds_available":0,
              "disabled_by_default":True,
              "is_ha_supported":True,
              "is_fortiview_supported":False
            },
            "fortianalyzer":{
              "is_available":True,
              "is_enabled":False,
              "overrides_global_faz":False
            },
            "fortianalyzer_cloud":{
              "is_available":False,
              "is_enabled":False,
              "overrides_global_faz_cloud":False
            },
            "forticloud":{
              "is_available":False,
              "is_enabled":False,
              "is_faz_cloud":False
            }
          },
          "log_device_default":"memory",
          "resolve_hostnames":True
        }
      }
    },
    "fext_enabled":True,
    "fext_vlan_mode":False,
    "snapshot_utc_time":1753662853000,
    "utc_last_reboot":1753656021000,
    "time_zone_offset":-720,
    "time_zone_text":"(GMT+12:00) Eniwetok, Kwajalein",
    "time_zone_db_name":"Pacific\/Kwajalein",
    "centrally_managed":False,
    "fortimanager_backup_mode":False,
    "fips_cc_enabled":False,
    "fips_ciphers_enabled":False,
    "vdom_mode":"",
    "management_vdom":"root",
    "conserve_mode":False,
    "image_sign_status":"certified",
    "bios_security_level":1,
    "need_fs_check":False,
    "carrier_mode":False,
    "has_hyperscale_license":False,
    "csf_enabled":False,
    "csf_group_name":"",
    "csf_upstream_ip":"",
    "csf_sync_mode":"default",
    "csf_object_sync_mode":"local",
    "ha_mode":2,
    "is_ha_master":1,
    "ngfw_mode":"profile-based",
    "forced_low_crypto":False,
    "has_log_disk":False,
    "has_local_config_revisions":True,
    "lenc_mode":False,
    "usg_mode":False,
    "admin_https_redirection":True,
    "config_save_mode":"automatic",
    "debug_supported_daemons":[
      "node",
      "httpsd",
      "cmdb",
      "miglogd",
      "csfd",
      "sslvpnd"
    ],
    "is_vm":False,
    "theme":"jade",
    "language_code":"en",
    "cmgmt_override_cookie_name":"CENTRAL_MGMT_OVERRIDE_8703991875265152462",
    "ccsrf_token_cookie_name":"ccsrftoken_8703991875265152462",
    "file_downloading_cookie_name":"FILE_DOWNLOADING_8703991875265152462",
    "autoscale_config_rec_override_cookie_name":"AUTOSCALE_CONFIG_REC_OVERRIDE_8703991875265152462",
    "initial_vdom":"root",
    "timeout_minutes":480,
    "features":{
      "gui-ipv6":False,
      "gui-replacement-message-groups":False,
      "gui-local-out":False,
      "gui-certificates":False,
      "gui-custom-language":False,
      "gui-wireless-opensecurity":False,
      "gui-display-hostname":True,
      "gui-fortigate-cloud-sandbox":False,
      "gui-firmware-upgrade-warning":True,
      "gui-allow-default-hostname":False,
      "gui-forticare-registration-setup-warning":True,
      "gui-cdn-usage":True,
      "switch-controller":True,
      "wireless-controller":True,
      "fortiextender":True,
      "fortitoken-cloud-service":True
    },
    "date_format":"yyyy/MM/dd",
    "date_format_device":"system",
    "security_rating_result_submission":True,
    "security_rating_run_on_schedule":True
  },
  "vdom":"root",
  "path":"web-ui",
  "name":"state",
  "action":"",
  "status":"success",
  "serial":"FGT60FTK20099VM6",
  "version":"v7.0.17",
  "build":682
}                                                                                                                                                                                                            ✓
"""